In [1]:
import polars as pl

df: pl.DataFrame = pl.read_csv("./ecommerce_dataset/2019-Nov.csv")

In [ ]:
df.select(pl.col('price').max().alias('max_price'),pl.col('price').min().alias('min_price'))

shape: (1, 2)
┌───────────┬───────────┐
│ max_price ┆ min_price │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ 2574.07   ┆ 0.0       │
└───────────┴───────────┘

In [5]:
df.shape

(67501979, 9)

In [10]:
df_top = df.head()
df_top

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬────────┬───────────┬────────────┐
│ event_time ┆ event_type ┆ product_id ┆ category_i ┆ … ┆ brand  ┆ price  ┆ user_id   ┆ user_sessi │
│ ---        ┆ ---        ┆ ---        ┆ d          ┆   ┆ ---    ┆ ---    ┆ ---       ┆ on         │
│ str        ┆ str        ┆ i64        ┆ ---        ┆   ┆ str    ┆ f64    ┆ i64       ┆ ---        │
│            ┆            ┆            ┆ i64        ┆   ┆        ┆        ┆           ┆ str        │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪════════╪═══════════╪════════════╡
│ 2019-11-01 ┆ view       ┆ 1003461    ┆ 2053013555 ┆ … ┆ xiaomi ┆ 489.07 ┆ 520088904 ┆ 4d3b30da-a │
│ 00:00:00   ┆            ┆            ┆ 631882655  ┆   ┆        ┆        ┆           ┆ 5e4-49df-b │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 1a8-ba5943 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 5000088    ┆ 2053013566 ┆ … ┆ janome ┆ 293.65 ┆ 530496790 ┆ 8e5f4f83-3 │
│ 00:00:00   ┆            ┆            ┆ 100866035  ┆   ┆        ┆        ┆           ┆ 66c-4f70-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 60e-ca7417 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 17302664   ┆ 2053013553 ┆ … ┆ creed  ┆ 28.31  ┆ 561587266 ┆ 755422e7-9 │
│ 00:00:01   ┆            ┆            ┆ 853497655  ┆   ┆        ┆        ┆           ┆ 040-477b-9 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ bd2-6a6e8f │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 3601530    ┆ 2053013563 ┆ … ┆ lg     ┆ 712.87 ┆ 518085591 ┆ 3bfb58cd-7 │
│ 00:00:01   ┆            ┆            ┆ 810775923  ┆   ┆        ┆        ┆           ┆ 892-48cc-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 020-2f17e6 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 1004775    ┆ 2053013555 ┆ … ┆ xiaomi ┆ 183.27 ┆ 558856683 ┆ 313628f1-6 │
│ 00:00:01   ┆            ┆            ┆ 631882655  ┆   ┆        ┆        ┆           ┆ 8b8-460d-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 4f6-cec7a8 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴────────┴───────────┴────────────┘

In [12]:
df_top.with_columns((pl.col('price')*100).alias('price2'))

shape: (5, 10)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬───────────┬───────────┬─────────┐
│ event_time ┆ event_type ┆ product_id ┆ category_i ┆ … ┆ price  ┆ user_id   ┆ user_sess ┆ price2  │
│ ---        ┆ ---        ┆ ---        ┆ d          ┆   ┆ ---    ┆ ---       ┆ ion       ┆ ---     │
│ str        ┆ str        ┆ i64        ┆ ---        ┆   ┆ f64    ┆ i64       ┆ ---       ┆ f64     │
│            ┆            ┆            ┆ i64        ┆   ┆        ┆           ┆ str       ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪═══════════╪═══════════╪═════════╡
│ 2019-11-01 ┆ view       ┆ 1003461    ┆ 2053013555 ┆ … ┆ 489.07 ┆ 520088904 ┆ 4d3b30da- ┆ 48907.0 │
│ 00:00:00   ┆            ┆            ┆ 631882655  ┆   ┆        ┆           ┆ a5e4-49df ┆         │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆           ┆ -b1a8-ba5 ┆         │
│            ┆            ┆            ┆            ┆   ┆        ┆           ┆ 943…      ┆         │
│ 2019-11-01 ┆ view       ┆ 5000088    ┆ 2053013566 ┆ … ┆ 293.65 ┆ 530496790 ┆ 8e5f4f83- ┆ 29365.0 │
│ 00:00:00   ┆            ┆            ┆ 100866035  ┆   ┆        ┆           ┆ 366c-4f70 ┆         │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆           ┆ -860e-ca7 ┆         │
│            ┆            ┆            ┆            ┆   ┆        ┆           ┆ 417…      ┆         │
│ 2019-11-01 ┆ view       ┆ 17302664   ┆ 2053013553 ┆ … ┆ 28.31  ┆ 561587266 ┆ 755422e7- ┆ 2831.0  │
│ 00:00:01   ┆            ┆            ┆ 853497655  ┆   ┆        ┆           ┆ 9040-477b ┆         │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆           ┆ -9bd2-6a6 ┆         │
│            ┆            ┆            ┆            ┆   ┆        ┆           ┆ e8f…      ┆         │
│ 2019-11-01 ┆ view       ┆ 3601530    ┆ 2053013563 ┆ … ┆ 712.87 ┆ 518085591 ┆ 3bfb58cd- ┆ 71287.0 │
│ 00:00:01   ┆            ┆            ┆ 810775923  ┆   ┆        ┆           ┆ 7892-48cc ┆         │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆           ┆ -8020-2f1 ┆         │
│            ┆            ┆            ┆            ┆   ┆        ┆           ┆ 7e6…      ┆         │
│ 2019-11-01 ┆ view       ┆ 1004775    ┆ 2053013555 ┆ … ┆ 183.27 ┆ 558856683 ┆ 313628f1- ┆ 18327.0 │
│ 00:00:01   ┆            ┆            ┆ 631882655  ┆   ┆        ┆           ┆ 68b8-460d ┆         │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆           ┆ -84f6-cec ┆         │
│            ┆            ┆            ┆            ┆   ┆        ┆           ┆ 7a8…      ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴───────────┴───────────┴─────────┘

In [19]:
lazy_min = df_top.with_columns(pl.col('price').min().alias('min_price')).lazy()
print(lazy_min)

naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

DF ["event_time", "event_type", "product_id", "category_id", ...]; PROJECT */10 COLUMNS

In [17]:
lazy_min.collect()

shape: (5, 10)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ event_time ┆ event_type ┆ product_i ┆ category_ ┆ … ┆ price  ┆ user_id   ┆ user_sess ┆ min_price │
│ ---        ┆ ---        ┆ d         ┆ id        ┆   ┆ ---    ┆ ---       ┆ ion       ┆ ---       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ f64    ┆ i64       ┆ ---       ┆ f64       │
│            ┆            ┆ i64       ┆ i64       ┆   ┆        ┆           ┆ str       ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 2019-11-01 ┆ view       ┆ 1003461   ┆ 205301355 ┆ … ┆ 489.07 ┆ 520088904 ┆ 4d3b30da- ┆ 28.31     │
│ 00:00:00   ┆            ┆           ┆ 563188265 ┆   ┆        ┆           ┆ a5e4-49df ┆           │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆        ┆           ┆ -b1a8-ba5 ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 943…      ┆           │
│ 2019-11-01 ┆ view       ┆ 5000088   ┆ 205301356 ┆ … ┆ 293.65 ┆ 530496790 ┆ 8e5f4f83- ┆ 28.31     │
│ 00:00:00   ┆            ┆           ┆ 610086603 ┆   ┆        ┆           ┆ 366c-4f70 ┆           │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆        ┆           ┆ -860e-ca7 ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 417…      ┆           │
│ 2019-11-01 ┆ view       ┆ 17302664  ┆ 205301355 ┆ … ┆ 28.31  ┆ 561587266 ┆ 755422e7- ┆ 28.31     │
│ 00:00:01   ┆            ┆           ┆ 385349765 ┆   ┆        ┆           ┆ 9040-477b ┆           │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆        ┆           ┆ -9bd2-6a6 ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ e8f…      ┆           │
│ 2019-11-01 ┆ view       ┆ 3601530   ┆ 205301356 ┆ … ┆ 712.87 ┆ 518085591 ┆ 3bfb58cd- ┆ 28.31     │
│ 00:00:01   ┆            ┆           ┆ 381077592 ┆   ┆        ┆           ┆ 7892-48cc ┆           │
│ UTC        ┆            ┆           ┆ 3         ┆   ┆        ┆           ┆ -8020-2f1 ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 7e6…      ┆           │
│ 2019-11-01 ┆ view       ┆ 1004775   ┆ 205301355 ┆ … ┆ 183.27 ┆ 558856683 ┆ 313628f1- ┆ 28.31     │
│ 00:00:01   ┆            ┆           ┆ 563188265 ┆   ┆        ┆           ┆ 68b8-460d ┆           │
│ UTC        ┆            ┆           ┆ 5         ┆   ┆        ┆           ┆ -84f6-cec ┆           │
│            ┆            ┆           ┆           ┆   ┆        ┆           ┆ 7a8…      ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [24]:
df.with_columns(pl.col('price').mean().over('brand').alias("average_by_brand")).filter(pl.col('brand')!='null')

shape: (58_283_744, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ event_time ┆ event_typ ┆ product_i ┆ category_ ┆ … ┆ price   ┆ user_id   ┆ user_sess ┆ average_b │
│ ---        ┆ e         ┆ d         ┆ id        ┆   ┆ ---     ┆ ---       ┆ ion       ┆ y_brand   │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64     ┆ i64       ┆ ---       ┆ ---       │
│            ┆ str       ┆ i64       ┆ i64       ┆   ┆         ┆           ┆ str       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2019-11-01 ┆ view      ┆ 1003461   ┆ 205301355 ┆ … ┆ 489.07  ┆ 520088904 ┆ 4d3b30da- ┆ 203.75644 │
│ 00:00:00   ┆           ┆           ┆ 563188265 ┆   ┆         ┆           ┆ a5e4-49df ┆ 9         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -b1a8-ba5 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 943…      ┆           │
│ 2019-11-01 ┆ view      ┆ 5000088   ┆ 205301356 ┆ … ┆ 293.65  ┆ 530496790 ┆ 8e5f4f83- ┆ 261.12846 │
│ 00:00:00   ┆           ┆           ┆ 610086603 ┆   ┆         ┆           ┆ 366c-4f70 ┆ 9         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -860e-ca7 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 417…      ┆           │
│ 2019-11-01 ┆ view      ┆ 17302664  ┆ 205301355 ┆ … ┆ 28.31   ┆ 561587266 ┆ 755422e7- ┆ 230.92271 │
│ 00:00:01   ┆           ┆           ┆ 385349765 ┆   ┆         ┆           ┆ 9040-477b ┆ 8         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -9bd2-6a6 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ e8f…      ┆           │
│ 2019-11-01 ┆ view      ┆ 3601530   ┆ 205301356 ┆ … ┆ 712.87  ┆ 518085591 ┆ 3bfb58cd- ┆ 470.50840 │
│ 00:00:01   ┆           ┆           ┆ 381077592 ┆   ┆         ┆           ┆ 7892-48cc ┆ 5         │
│ UTC        ┆           ┆           ┆ 3         ┆   ┆         ┆           ┆ -8020-2f1 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 7e6…      ┆           │
│ 2019-11-01 ┆ view      ┆ 1004775   ┆ 205301355 ┆ … ┆ 183.27  ┆ 558856683 ┆ 313628f1- ┆ 203.75644 │
│ 00:00:01   ┆           ┆           ┆ 563188265 ┆   ┆         ┆           ┆ 68b8-460d ┆ 9         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -84f6-cec ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 7a8…      ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 2019-11-30 ┆ view      ┆ 12301059  ┆ 205301355 ┆ … ┆ 266.16  ┆ 562661595 ┆ 7165dc28- ┆ 276.74781 │
│ 23:59:57   ┆           ┆           ┆ 631135994 ┆   ┆         ┆           ┆ 9cba-40a0 ┆ 1         │
│ UTC        ┆           ┆           ┆ 7         ┆   ┆         ┆           ┆ -9ed8-76f ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ d90…      ┆           │
│ 2019-11-30 ┆ view      ┆ 28719425  ┆ 205301356 ┆ … ┆ 62.81   ┆ 545223467 ┆ 734c5eef- ┆ 68.774643 │
│ 23:59:58   ┆           ┆           ┆ 563949256 ┆   ┆         ┆           ┆ 0742-4f8b ┆           │
│ UTC        ┆           ┆           ┆ 9         ┆   ┆         ┆           ┆ -9d22-48f ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 75b…      ┆           │
│ 2019-11-30 ┆ view      ┆ 1004833   ┆ 205301355 ┆ … ┆ 167.03  ┆ 557794415 ┆ 6fecf566- ┆ 356.11645 │
│ 23:59:59   ┆           ┆           ┆ 563188265 ┆   ┆         ┆           ┆ ebb0-4e70 ┆ 8         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -a243-cdc ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 13c…      ┆           │
│ 2019-11-30 ┆ view      ┆ 2701706   ┆ 205301356 ┆ … ┆ 566.27  ┆ 531607492 ┆ 368ddc8b- ┆ 356.11645 │
│ 23:59:59   ┆           ┆           ┆ 391143922 ┆   ┆         ┆           ┆ 5db9-40fb ┆ 8         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -b7ff-b65 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ 82a…      ┆           │
│ 2019-11-30 ┆ view      ┆ 1004233   ┆ 205301355 ┆ … ┆ 1312.52 ┆ 579969851 ┆ 90aca71c- ┆ 826.20840 │
│ 23:59:59   ┆           ┆           ┆ 563188265 ┆   ┆         ┆           ┆ ed8a-4670 ┆ 5         │
│ UTC        ┆           ┆           ┆ 5         ┆   ┆         ┆           ┆ -866a-761 ┆           │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ eba…      ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [31]:
df_top

shape: (5, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬────────┬───────────┬────────────┐
│ event_time ┆ event_type ┆ product_id ┆ category_i ┆ … ┆ brand  ┆ price  ┆ user_id   ┆ user_sessi │
│ ---        ┆ ---        ┆ ---        ┆ d          ┆   ┆ ---    ┆ ---    ┆ ---       ┆ on         │
│ str        ┆ str        ┆ i64        ┆ ---        ┆   ┆ str    ┆ f64    ┆ i64       ┆ ---        │
│            ┆            ┆            ┆ i64        ┆   ┆        ┆        ┆           ┆ str        │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪════════╪═══════════╪════════════╡
│ 2019-11-01 ┆ view       ┆ 1003461    ┆ 2053013555 ┆ … ┆ xiaomi ┆ 489.07 ┆ 520088904 ┆ 4d3b30da-a │
│ 00:00:00   ┆            ┆            ┆ 631882655  ┆   ┆        ┆        ┆           ┆ 5e4-49df-b │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 1a8-ba5943 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 5000088    ┆ 2053013566 ┆ … ┆ janome ┆ 293.65 ┆ 530496790 ┆ 8e5f4f83-3 │
│ 00:00:00   ┆            ┆            ┆ 100866035  ┆   ┆        ┆        ┆           ┆ 66c-4f70-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 60e-ca7417 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 17302664   ┆ 2053013553 ┆ … ┆ creed  ┆ 28.31  ┆ 561587266 ┆ 755422e7-9 │
│ 00:00:01   ┆            ┆            ┆ 853497655  ┆   ┆        ┆        ┆           ┆ 040-477b-9 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ bd2-6a6e8f │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 3601530    ┆ 2053013563 ┆ … ┆ lg     ┆ 712.87 ┆ 518085591 ┆ 3bfb58cd-7 │
│ 00:00:01   ┆            ┆            ┆ 810775923  ┆   ┆        ┆        ┆           ┆ 892-48cc-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 020-2f17e6 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
│ 2019-11-01 ┆ view       ┆ 1004775    ┆ 2053013555 ┆ … ┆ xiaomi ┆ 183.27 ┆ 558856683 ┆ 313628f1-6 │
│ 00:00:01   ┆            ┆            ┆ 631882655  ┆   ┆        ┆        ┆           ┆ 8b8-460d-8 │
│ UTC        ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ 4f6-cec7a8 │
│            ┆            ┆            ┆            ┆   ┆        ┆        ┆           ┆ …          │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴────────┴───────────┴────────────┘

In [ ]:
df.group_by('brand').agg(pl.col('price').sum()).filter(pl.col('price')<500).sort('price').head(5)

shape: (5, 2)
┌────────────────────────┬───────┐
│ brand                  ┆ price │
│ ---                    ┆ ---   │
│ str                    ┆ f64   │
╞════════════════════════╪═══════╡
│ dalianhantaitradecoltd ┆ 4.97  │
│ viteks                 ┆ 5.04  │
│ garant                 ┆ 5.86  │
│ arpenaz                ┆ 6.69  │
│ motorcraft             ┆ 6.69  │
└────────────────────────┴───────┘

In [35]:
df.group_by(['brand','event_type']).agg(pl.col('price').mean()).filter(pl.col('brand') == 'xiaomi')

shape: (3, 3)
┌────────┬────────────┬────────────┐
│ brand  ┆ event_type ┆ price      │
│ ---    ┆ ---        ┆ ---        │
│ str    ┆ str        ┆ f64        │
╞════════╪════════════╪════════════╡
│ xiaomi ┆ cart       ┆ 173.745558 │
│ xiaomi ┆ purchase   ┆ 164.878257 │
│ xiaomi ┆ view       ┆ 206.183149 │
└────────┴────────────┴────────────┘